import { PDFDocument, StandardFonts, rgb, type PDFPage, type PDFFont } from "pdf-lib";

export type PolicyIssueInput = {
  policyNumber: string;
  memberNameEn: string;
  memberNameAr?: string;
  emiratesId?: string;
  insurer: string;
  planName: string;
  tpa: string;
  network: string;
  effectiveDate: string;
  expiryDate: string;
  emergencyPhone: string;
  annualPremiumAed: number;
};

function drawLabelValueDarkCard(
  page: PDFPage,
  font: PDFFont,
  bold: PDFFont,
  x: number,
  y: number,
  label: string,
  value: string,
) {
  page.drawText(label, { x, y, size: 8, font: bold, color: rgb(0.55, 0.6, 0.68) });
  page.drawText(value, { x, y: y - 14, size: 11, font, color: rgb(0.95, 0.96, 0.98) });
  return y - 36;
}

export async function buildEcardPdf(input: PolicyIssueInput): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([420, 280]);
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  page.drawRectangle({
    x: 0,
    y: 0,
    width: 420,
    height: 280,
    color: rgb(0.03, 0.11, 0.25),
  });
  page.drawText("InnoCare X", { x: 24, y: 248, size: 14, font: bold, color: rgb(0.2, 0.45, 0.95) });
  page.drawText("Digital health card", { x: 24, y: 228, size: 10, font, color: rgb(0.75, 0.78, 0.85) });

  let y = 200;
  y = drawLabelValueDarkCard(page, font, bold, 24, y, "Member", input.memberNameEn);
  if (input.memberNameAr) {
    y = drawLabelValueDarkCard(page, font, bold, 24, y, "Member (AR)", input.memberNameAr);
  }
  if (input.emiratesId) {
    y = drawLabelValueDarkCard(page, font, bold, 24, y, "Emirates ID", input.emiratesId);
  }
  y = drawLabelValueDarkCard(page, font, bold, 24, y, "Policy", input.policyNumber);
  y = drawLabelValueDarkCard(page, font, bold, 24, y, "Insurer", input.insurer);
  y = drawLabelValueDarkCard(page, font, bold, 24, y, "Plan", input.planName);
  y = drawLabelValueDarkCard(page, font, bold, 24, y, "TPA / Network", `${input.tpa} — ${input.network}`);
  drawLabelValueDarkCard(page, font, bold, 220, 200, "Valid from", input.effectiveDate);
  drawLabelValueDarkCard(page, font, bold, 220, 164, "Valid to", input.expiryDate);
  drawLabelValueDarkCard(page, font, bold, 220, 128, "Emergency", input.emergencyPhone);

  page.drawText("Demo issuance — not legally binding.", {
    x: 24,
    y: 16,
    size: 7,
    font,
    color: rgb(0.55, 0.58, 0.65),
  });

  return pdf.save();
}

export async function buildCertificatePdf(input: PolicyIssueInput): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595.28, 841.89]);
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  page.drawText("Certificate of health insurance", {
    x: 48,
    y: 780,
    size: 20,
    font: bold,
    color: rgb(0.05, 0.1, 0.2),
  });
  page.drawText("InnoCare X — UAE distribution demo", {
    x: 48,
    y: 752,
    size: 10,
    font,
    color: rgb(0.35, 0.38, 0.42),
  });

  let y = 700;
  const lines: [string, string][] = [
    ["Policy number", input.policyNumber],
    ["Member", input.memberNameEn],
    ["Emirates ID", input.emiratesId || "—"],
    ["Insurer", input.insurer],
    ["Plan", input.planName],
    ["Annual premium (AED)", String(input.annualPremiumAed)],
    ["Coverage period", `${input.effectiveDate} to ${input.expiryDate}`],
    ["TPA", input.tpa],
    ["Network tier", input.network],
  ];
  for (const [lab, val] of lines) {
    page.drawText(lab, { x: 48, y, size: 9, font: bold, color: rgb(0.45, 0.48, 0.52) });
    page.drawText(val, { x: 220, y, size: 11, font, color: rgb(0.1, 0.12, 0.18) });
    y -= 28;
  }

  page.drawText(
    "This certificate is generated by the InnoCare X demo portal for testing. It is not an insurer-issued policy document.",
    { x: 48, y: 120, size: 9, font, color: rgb(0.4, 0.42, 0.45) },
  );

  return pdf.save();
}
